[package]
name = "squeeze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.1", features = ["sync", "time", "rt"] }

[dev-dependencies]
tokio = { version = "1.28.1", features = ["rt", "macros"] }
uuid = "1.3.2"
